-- MySQL Script generated by MySQL Workbench
-- Thu Nov 26 10:30:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ticket_booking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ticket_booking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticket_booking` DEFAULT CHARACTER SET utf8 ;
USE `ticket_booking` ;

-- -----------------------------------------------------
-- Table `ticket_booking`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_booking`.`movies` ;

CREATE TABLE IF NOT EXISTS `ticket_booking`.`movies` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `genre` VARCHAR(60) NULL,
  `year` SMALLINT UNSIGNED NULL,
  `rating` DECIMAL(4,2) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket_booking`.`cinema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_booking`.`cinema` ;

CREATE TABLE IF NOT EXISTS `ticket_booking`.`cinema` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket_booking`.`screens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_booking`.`screens` ;

CREATE TABLE IF NOT EXISTS `ticket_booking`.`screens` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cinema_id` INT UNSIGNED NOT NULL,
  `capacity` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `cinema_id_idx` (`cinema_id` ASC) VISIBLE,
  CONSTRAINT `cinema_id`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `ticket_booking`.`cinema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket_booking`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_booking`.`events` ;

CREATE TABLE IF NOT EXISTS `ticket_booking`.`events` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `movie_id` INT UNSIGNED NOT NULL,
  `screen_id` INT UNSIGNED NOT NULL,
  `date` DATETIME NOT NULL,
  `ticket_price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `tickets_available` INT UNSIGNED NULL,
  INDEX `movie_id_idx` (`movie_id` ASC) VISIBLE,
  INDEX `screen_id_idx` (`screen_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `ticket_booking`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `screen_id`
    FOREIGN KEY (`screen_id`)
    REFERENCES `ticket_booking`.`screens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket_booking`.`bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket_booking`.`bookings` ;

CREATE TABLE IF NOT EXISTS `ticket_booking`.`bookings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_id` INT UNSIGNED NOT NULL,
  `guest_name` VARCHAR(100) NOT NULL,
  `tickets_booked` INT UNSIGNED NOT NULL,
  `tickets_value_total` DECIMAL(7,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `event_id_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `ticket_booking`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
